# Generated by Django 4.0.4 on 2022-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='user',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('1m', 'یک ماهه'), ('3m', 'سه ماهه'), ('6m', 'شش ماهه'), ('1y', 'یک ساله')], default=None, max_length=2, null=True, verbose_name='مدت زمان دوره'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
