# Generated by Django 4.0.4 on 2022-05-03 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0003_user_course_validity_up_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_validity_up_to',
        ),
        migrations.AddField(
            model_name='user',
            name='course_validity_up_to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 10, 27, 52, 600881, tzinfo=utc), verbose_name='اعتبار دوره تا تاریخ'),
        ),
    ]
