# Generated by Django 4.0.4 on 2022-05-03 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0005_categorycourse_alter_user_course_validity_up_to_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycourse',
            options={'verbose_name': 'دسته بندی دوره', 'verbose_name_plural': 'دسته بندی دورها'},
        ),
        migrations.AlterField(
            model_name='categorycourse',
            name='slug',
            field=models.SlugField(verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='categorycourse',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='categorycourse',
            name='title',
            field=models.CharField(default=None, max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_validity_up_to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 15, 45, 50, 561077, tzinfo=utc), verbose_name='اعتبار دوره تا تاریخ'),
        ),
    ]
