# Generated by Django 4.0.4 on 2022-05-03 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0006_alter_categorycourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_course',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_course_user', to='fitshow_user.categorycourse', verbose_name='دوره کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_validity_up_to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 16, 44, 2, 804822, tzinfo=utc), verbose_name='اعتبار دوره تا تاریخ'),
        ),
    ]
