# Generated by Django 4.0.4 on 2022-05-03 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0007_user_category_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_validity_up_to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 17, 16, 48, 212451, tzinfo=utc), verbose_name='اعتبار دوره تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
