# Generated by Django 4.0.4 on 2022-05-04 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitShowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره موبایل')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='سن')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('course_duration', models.CharField(blank=True, choices=[('30', 'یک ماهه'), ('90', 'سه ماهه'), ('180', 'شش ماهه'), ('365', 'یک ساله')], default=None, max_length=3, null=True, verbose_name='مدت زمان دوره')),
                ('course_validity_up_to_date', models.DateTimeField(default=datetime.datetime(2022, 5, 4, 10, 57, 20, 408815, tzinfo=utc), verbose_name='اعتبار دوره تا تاریخ')),
                ('category_course', models.ManyToManyField(blank=True, null=True, related_name='category_course_user', to='fitshow_user.categorycourse', verbose_name='دوره کاربر')),
            ],
        ),
    ]
