# Generated by Django 4.0.4 on 2022-05-04 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitshow_user', '0011_fitshowuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitshowuser',
            options={'verbose_name': 'کاربر فیت شو', 'verbose_name_plural': 'کاربران فیت شو'},
        ),
        migrations.AddField(
            model_name='fitshowuser',
            name='firstname',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AddField(
            model_name='fitshowuser',
            name='fullname',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AddField(
            model_name='fitshowuser',
            name='lastname',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AlterField(
            model_name='fitshowuser',
            name='course_validity_up_to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 11, 6, 6, 403900, tzinfo=utc), verbose_name='اعتبار دوره تا تاریخ'),
        ),
    ]
